sudo: true
language: haskell

git:
  depth: 5

cache:
  directories:
  - "$HOME/.cabal/store"
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

jobs:
  include:
  - ghc: 8.6.5
    env: SNAPSHOT="lts-14.22"
  - ghc: 8.6.4
    env: SNAPSHOT="lts-13.19"
  - ghc: 8.6.3
    env: SNAPSHOT="lts-13.11"
  - ghc: 8.4.4
    env: SNAPSHOT="lts-12.26"

install:
  - |
    # install stack
    curl -sSL https://get.haskellstack.org/ | sh

    # build project with stack
    stack --version
    stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks --resolver=$SNAPSHOT

script:
  - |
    stack test --system-ghc

notifications:
  email: false
